import Head from "next/head";
import Image from "next/image";
import SearchModal from "../components/startpage/SearchModal";
import StartPageComponent from "../components/startpage/StartPageComponent";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import { SkurlisteProps } from "../tsmodules/posterModule";

export default function Home({
  skurliste,
  poster,
  setSkurlisteInfo,
  skurlisteInfo,
  setPostInfo,
}: SkurlisteProps) {
  const [openSearchModal, setOpenSearchModal] = useState(false);

  return (
    <div>
      <Head>
        <title>Postarkiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {openSearchModal && (
        <SearchModal
          setOpenSearchModal={setOpenSearchModal}
          poster={poster}
          setPostInfo={setPostInfo}
          setSkurlisteInfo={function (
            value: React.SetStateAction<string>
          ): void {
            throw new Error("Function not implemented.");
          }}
          skurlisteInfo={undefined}
          setSearchResultModal={function (
            value: React.SetStateAction<boolean>
          ): void {
            throw new Error("Function not implemented.");
          }}
        />
      )}
      <StartPageComponent
        skurliste={skurliste}
        setOpenSearchModal={setOpenSearchModal}
        setSkurlisteInfo={setSkurlisteInfo}
        skurlisteInfo={skurlisteInfo}
        poster={poster}
        setPostInfo={setPostInfo}
      />
    </div>
  );
}
