import Head from "next/head";
import Image from "next/image";
import SearchModal from "../components/startpage/SearchModal";
import StartPageComponent from "../components/startpage/StartPageComponent";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { SkurlisteProps } from "../tsmodules/posterModule";

export default function Home({
  skurliste,
  poster,
  setSkurlisteInfo,
  skurlisteInfo,
  setPostInfo,
  searchResultModal,
  setSearchResultModal,
  setFinalSkurlisteInfo,
  setOpenDot,
}: SkurlisteProps) {
  const [openSearchModal, setOpenSearchModal] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const r = document.querySelector(":root");

      function myFunction_get() {
        // Get the styles (properties and values) for the root
        var rs = getComputedStyle(r);
        // Alert the value of the --blue variable
        r.style.setProperty("--primary", "lightblue");
        r.style.setProperty("--table-bg", "red");
        console.log(
          "The value of --primary is: " + rs.getPropertyValue("--primary")
        );
      }

      myFunction_get();
    }
  }, []);

  return (
    <div className={styles.indexContainer}>
      <Head>
        <title>Postarkiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {openSearchModal && (
        <SearchModal
          setOpenSearchModal={setOpenSearchModal}
          poster={poster}
          setPostInfo={setPostInfo}
          setSkurlisteInfo={setSkurlisteInfo}
          skurlisteInfo={undefined}
          setSearchResultModal={function (
            value: React.SetStateAction<boolean>
          ): void {
            throw new Error("Function not implemented.");
          }}
          update={false}
          setUpdate={function (value: React.SetStateAction<boolean>): void {
            throw new Error("Function not implemented.");
          }}
          setOpenDot={function (value: React.SetStateAction<boolean>): void {
            throw new Error("Function not implemented.");
          }}
        />
      )}
      <StartPageComponent
        skurliste={skurliste}
        setOpenSearchModal={setOpenSearchModal}
        setSkurlisteInfo={setSkurlisteInfo}
        skurlisteInfo={skurlisteInfo}
        poster={poster}
        setPostInfo={setPostInfo}
        setSearchResultModal={setSearchResultModal}
        searchResultModal={searchResultModal}
        setFinalSkurlisteInfo={setFinalSkurlisteInfo}
        setOpenDot={setOpenDot}
      />
    </div>
  );
}
