import Head from "next/head";
import Image from "next/image";
import SearchModal from "../components/startpage/SearchModal";
import StartPageComponent from "../components/startpage/StartPageComponent";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { SkurlisteProps } from "../tsmodules/posterModule";

export default function Home({
  skurliste,
  poster,
  setSkurlisteInfo,
  skurlisteInfo,
  setPostInfo,
  searchResultModal,
  setSearchResultModal,
  setFinalSkurlisteInfo,
  setOpenDot,
}: SkurlisteProps) {
  const [openSearchModal, setOpenSearchModal] = useState(false);

  function greenTheme() {
    if (typeof window !== "undefined") {
      const r: any = document.querySelector(":root");
      // Get the styles (properties and values) for the root
      var rs = getComputedStyle(r);
      // Alert the value of the --blue variable
      r.style.setProperty("--primary", "#17252a");
      r.style.setProperty("--primary-text", "#def2f1");
      r.style.setProperty("--table-bg", "#29424b");
      r.style.setProperty("--outer", "#2b7a78");
      r.style.setProperty("--outer-text", "#ceeeda");
      r.style.setProperty("--center", "#def2f1");
      r.style.setProperty("--center-text", "#436268");
      r.style.setProperty("--text", "#45a29e");
      r.style.setProperty("--hover", "#395352");
      r.style.setProperty("--running", "#26706d");
      r.style.setProperty("--finish", "#221f1f");
      r.style.setProperty("--finish-text", "#394046");
      r.style.setProperty("--outer2", "#5d5c61");
      r.style.setProperty("--outer-text2", "#ceeeda");
      r.style.setProperty("--center2", "#7395ae");
      r.style.setProperty("--center-text2", "#3f2f29");
      r.style.setProperty("--mark", "#9c9c9c");
    }
  }

  useEffect(() => {
    greenTheme();
  }, []);

  return (
    <div className={styles.indexContainer}>
      <Head>
        <title>Postarkiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {openSearchModal && (
        <SearchModal
          setOpenSearchModal={setOpenSearchModal}
          poster={poster}
          setPostInfo={setPostInfo}
          setSkurlisteInfo={setSkurlisteInfo}
          skurlisteInfo={undefined}
          setSearchResultModal={function (
            value: React.SetStateAction<boolean>
          ): void {
            throw new Error("Function not implemented.");
          }}
          update={false}
          setUpdate={function (value: React.SetStateAction<boolean>): void {
            throw new Error("Function not implemented.");
          }}
          setOpenDot={function (value: React.SetStateAction<boolean>): void {
            throw new Error("Function not implemented.");
          }}
        />
      )}
      <StartPageComponent
        skurliste={skurliste}
        setOpenSearchModal={setOpenSearchModal}
        setSkurlisteInfo={setSkurlisteInfo}
        skurlisteInfo={skurlisteInfo}
        poster={poster}
        setPostInfo={setPostInfo}
        setSearchResultModal={setSearchResultModal}
        searchResultModal={searchResultModal}
        setFinalSkurlisteInfo={setFinalSkurlisteInfo}
        setOpenDot={setOpenDot}
      />
    </div>
  );
}
